/**
 * Automatically generated exercise plan video mapping links.
 * Generated on: 2026-08-08T21:00:35.497Z
 */

export const WORKOUT_VIDEO_MAPPING: Record<string, string> = {
  "Incline Dumbbell Press": "/videos/workouts/shoulders/Dumbbell%20Incline%20Hammer%20Press.mp4",
  "Pec Deck Fly": "/videos/workouts/chest/Lever%20Pec%20Deck%20Fly.mp4",
  "Lat Pulldown": "/videos/workouts/back/Reverse%20Grip%20Machine%20Lat%20Pulldown.mp4",
  "Face Pulls": "/videos/workouts/back/Pull-up%20(shoulder%20grip).mp4",
  "Leg Extension": "/videos/workouts/hips/Lever%20Leg%20Extension.mp4",
  "Leg Curl": "/videos/workouts/hips/Band%20Leg%20Curl.mp4",
  "Calf Raises": "/videos/workouts/calves/Donkey%20Calf%20Raise.mp4",
  "Lateral Delt Raises": "/videos/workouts/shoulders/Cable%20Lateral%20Raise.mp4",
  "Plank": "/videos/workouts/abs/Side%20Bridge%20-%20Side%20Plank.mp4",
  "Cardio": "/videos/workouts/cardio/Cardio%20Exercises.mp4",
  "Incline Bench Press": "/videos/workouts/chest/Barbell%20Incline%20Bench%20Press.mp4",
  "Flat Dumbbell Fly": "/videos/workouts/chest/Dumbbell%20Fly.mp4",
  "Machine Incline Press": "/videos/workouts/shoulders/Dumbbell%20Incline%20Hammer%20Press.mp4",
  "Dumbbell Shoulder Press": "/videos/workouts/shoulders/Dumbbell%20Alternate%20Shoulder%20Press.mp4",
  "Side Lateral Raises": "/videos/workouts/shoulders/Cable%20Lateral%20Raise.mp4",
  "Tricep Pushdown": "/videos/workouts/triceps/Band%20Triceps%20Pushdown.mp4",
  "T-Bar Row": "/videos/workouts/back/Lever%20T-bar%20Row.mp4",
  "Seated Cable Row": "/videos/workouts/back/Cable%20Seated%20Row%20(normal%20grip).mp4",
  "Dumbbell Shrugs": "/videos/workouts/trapezius/Dumbbell%20Shrug.mp4",
  "Dumbbell Bicep Curls": "/videos/workouts/biceps/Dumbbell%20Biceps%20Curl.mp4",
  "Preacher Curls": "/videos/workouts/biceps/Lever%20Preacher%20Curl.mp4",
  "Barbell Squats": "/videos/workouts/hips/Classic%20Barbell%20Squat.mp4",
  "Leg Press": "/videos/workouts/hips/Smith%20Leg%20Press.mp4",
  "Walking Lunges": "/videos/workouts/hips/Barbell%20Lunge.mp4",
  "Back Extension": "/videos/workouts/back/Lever%20Back%20Extension.mp4",
  "Incline Barbell Press": "/videos/workouts/chest/Barbell%20Incline%20Bench%20Press.mp4",
  "Flat Dumbbell Press": "/videos/workouts/shoulders/Dumbbell%20Arnold%20Press.mp4",
  "Cable Fly (Low to High) [SS]": "/videos/workouts/chest/Cable%20Lying%20Fly%2C%20Flat%20Bench%20Cable%20Fly.mp4",
  "Push-Ups [SS]": "/videos/workouts/chest/Push-ups.mp4",
  "Seated DB Shoulder Press": "/videos/workouts/shoulders/Smith%20Seated%20Shoulder%20Press.mp4",
  "Lateral Raises [DS]": "/videos/workouts/shoulders/Cable%20Lateral%20Raise.mp4",
  "Tricep Rope Pushdown [DS]": "/videos/workouts/triceps/Band%20Triceps%20Pushdown.mp4",
  "Deadlift / Rack Pulls": "/videos/workouts/back/Band%20Pull%20Through.mp4",
  "Weighted Pull-Ups / Lat Pulldown": "/videos/workouts/back/Pull-up%20(shoulder%20grip).mp4",
  "Romanian Deadlifts (RDL)": "/videos/workouts/back/Dumbbell%20Deadlift.mp4",
  "Hammer Curls [DS]": "/videos/workouts/biceps/Dumbbell%20Incline%20Hammer%20Curl.mp4",
  "Incline Dumbbell Press [GS A]": "/videos/workouts/shoulders/Dumbbell%20Incline%20Hammer%20Press.mp4",
  "Cable Pulley Row (Overhand grip) [GS A]": "/videos/workouts/back/Cable%20Seated%20Row%20(normal%20grip).mp4",
  "EZ Barbell Preacher Curl [GS A]": "/videos/workouts/biceps/EZ%20Barbell%20Biceps%20Curl.mp4",
  "Incline DB Fly [GS B]": "/videos/workouts/chest/Dumbbell%20Incline%20Fly.mp4",
  "Lat Pulldown (Neutral grip) [GS B]": "/videos/workouts/back/Reverse%20Grip%20Machine%20Lat%20Pulldown.mp4",
  "Incline DB Dumbbell Curls [GS B]": "/videos/workouts/biceps/Dumbbell%20Incline%20Biceps%20Curl.mp4",
  "Barbell Chest Press [GS A]": "/videos/workouts/chest/Barbell%20Bench%20Press.mp4",
  "Lat Pulldown (Wide grip) [GS A]": "/videos/workouts/back/Reverse%20Grip%20Machine%20Lat%20Pulldown.mp4",
  "Hammer Curls [GS A]": "/videos/workouts/biceps/Dumbbell%20Incline%20Hammer%20Curl.mp4",
  "Cable Fly (High to Low) [GS B]": "/videos/workouts/chest/Cable%20Lying%20Fly%2C%20Flat%20Bench%20Cable%20Fly.mp4",
  "One Arm DB Row [GS B]": "/videos/workouts/back/Band%20One%20Arm%20Twisting%20Seated%20Row.mp4",
  "Concentration Curls [GS B]": "/videos/workouts/biceps/Dumbbell%20Concentration%20Curl.mp4",
  "Overhead DB Extension [GS A]": "/videos/workouts/triceps/Band%20Overhead%20Triceps%20Extension.mp4",
  "DB Kickbacks (Both arms) [GS A]": "/videos/workouts/triceps/Dumbbell%20Kickback.mp4",
  "Lying DB Tricep Extension [GS B]": "/videos/workouts/triceps/Cable%20Lying%20Triceps%20Extension.mp4",
  "Tricep Pushdown (V-Bar) [GS B]": "/videos/workouts/triceps/Band%20Triceps%20Pushdown.mp4",
  "Overhead Cable Extension [GS A]": "/videos/workouts/triceps/Cable%20Overhead%20Triceps%20Extension%20(rope%20attachment).mp4",
  "Cable Pushdown (Underhand grip) [GS A]": "/videos/workouts/triceps/Cable%20Pushdown%20(rope%20attachment).mp4",
  "Dumbbell Curls (Alternate) [GS B]": "/videos/workouts/biceps/Dumbbell%20Biceps%20Curl.mp4",
  "Cable Curl (Straight Bar) [GS B]": "/videos/workouts/biceps/Cable%20One%20Arm%20Curl.mp4",
  "Behind the Neck Press": "/videos/workouts/shoulders/Barbell%20Seated%20Behind%20Head%20Military%20Press.mp4",
  "DB Lateral Raises (Standing)": "/videos/workouts/shoulders/Cable%20Lateral%20Raise.mp4",
  "Dumbbell Front Raises": "/videos/workouts/shoulders/Dumbbell%20Front%20Raise.mp4",
  "Smith Machine Shrugs": "/videos/workouts/hips/Smith%20Chair%20Squat.mp4",
  "Smith Machine Calf Raises": "/videos/workouts/calves/Smith%20Calf%20Raise.mp4",
  "Leg Curls [SS]": "/videos/workouts/hips/Band%20Leg%20Curl.mp4",
  "Leg Extension [SS]": "/videos/workouts/hips/Lever%20Leg%20Extension.mp4",
  "Calf Raises [DS]": "/videos/workouts/calves/Donkey%20Calf%20Raise.mp4"
};
